services:
  frontend:
    container_name: frontend
    build:
      context: ./camagru/frontend
      dockerfile: Dockerfile
    volumes:
      - ./camagru/frontend/application_files:/usr/share/nginx/html
      - ./camagru/backend/uploads:/uploads
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: ./camagru/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./camagru/backend/uploads:/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 10s
      retries: 20
      start_period: 10s

volumes:
  postgres_data:
  uploads:

networks:
  app_network:
